import { Card } from './fb.service';

export const deck: Card[] = [
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K1A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K1B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K1C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K1D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K2A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K2B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K2C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K2D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K3A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K3B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K3C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K3D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K4A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K4B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K4C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K4D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K5A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K5B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K5C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K5D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K6A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K6B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K6C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K6D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K7A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K7B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K7C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K7D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K8A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K8B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K8C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K8D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K9A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K9B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K9C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'katak', id: "K9D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B1A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B1B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B1C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B1D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B2A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B2B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B2C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B2D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B3A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B3B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B3C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B3D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B4A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B4B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B4C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B4D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B5A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B5B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B5C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B5D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B6A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B6B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B6C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B6D", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B7A", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B7B", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B7C", isFront: true, player: 0 },
    { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B7D", isFront: true, player: 0 }
    // { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B8A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B8B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B8C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B8D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B9A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B9B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B9C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'bamboo', id: "B9D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O1A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O1B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O1C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O1D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O2A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O2B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O2C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O2D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O3A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O3B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O3C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O3D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O4A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O4B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O4C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O4D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O5A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O5B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O5C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O5D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O6A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O6B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O6C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O6D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O7A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O7B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O7C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O7D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O8A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O8B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O8C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O8D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O9A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O9B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O9C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'ball', id: "O9D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W1A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W1B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W1C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W1D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W2A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W2B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W2C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W2D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W3A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W3B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W3C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W3D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W4A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W4B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W4C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W4D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W5A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W5B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W5C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W5D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W6A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W6B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W6C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W6D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W7A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W7B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W7C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W7D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W8A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W8B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W8C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W8D", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W9A", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W9B", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W9C", isFront: true, player: 0 },
    // { rotation: '0,0,0', x: 0, y: 0, group: 'winces', id: "W9D", isFront: true, player: 0 }
]